### ISSUE TITLE
elmelmelmelmelmelmelmelmelmelmelmelmelmelmelixir

### ISSUE THREAD

**Issue by finnhodgkin** [Akin909/go-game-of-life#1]
:no_good_man: :arrow_forward:

 
:+1: :deciduous_tree:

**Comment by akinsho** [comment]
Closed due to the nonsensical nature of the issue!! @finnhodgkin

**Comment by finnhodgkin** [comment]
But it's still open :laughing:

**Comment by finnhodgkin** [comment]
Soz closing now :heart:
